### ISSUE TITLE
AttributeError: 'Gitlab' object has no attribute 'Project'

### ISSUE THREAD

**Issue by EtreRe** [ajcrowe/sentry-gitlab#17]
Hello all,

I'm using GitLab Community Edition 8.11.2

I have tried to install sentry-gitlab with pip or with cloning the repo.
I have also tried to use the repo name or the repo id.

And everytime i have this error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 175, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/group_plugin_action.py", line 25, in handle
    response = plugin.get_view_response(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/base/v1.py", line 296, in get_view_response
    response = self.view(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/issue.py", line 226, in view
    request=request,
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_gitlab/plugin.py", line 88, in create_issue
AttributeError: 'Gitlab' object has no attribute 'Project'
[ERROR] django.request: Internal Server Error: /sentry/php-error/issues/2263/actions/gitlab/
```

Do you know why ?

Thank you.

**Comment by jmatsushita** [comment]
Same error here! @ajcrowe Could it be that the API changed? I'm also using Gitlab 8.11(.5)

**Comment by jmatsushita** [comment]
Maybe it's related to #11 ?

**Comment by EtreRe** [comment]
Like I said, I have tried to use de repo id but didn't work.

**Comment by lippoliv** [comment]
Seems also rasing my original issue https://github.com/getsentry/sentry-plugins/issues/34

I use GitLab 8.12.4

**Comment by lippoliv** [comment]
👍

**Comment by mattrobenolt** [comment]
I can only assume a version bump if `python-gitlab` has completely changed their API and we aren't correctly pinning. :(

**Comment by BooksLiu** [comment]
@EtreRe 
Hi,maybe it's too late,but I have an idea to solve this problem.

First:you can `source activate`.
Second:you can execute `pip uninstall sentry-gitlab`,then you should execute `pip install sentry-plugins=={your sentry version}`
Last:you can restart sentry

I using this method to solve this question,I hope it is helpful for you.
