### ISSUE TITLE
Error repositories

### ISSUE THREAD

**Issue by pcmalves** [ajcrowe/sentry-gitlab#19]
Hello,
I am trying to configure the repositories option in my sentry version **8.18.0**.

Select ***Add Repository*** > ***Save Changes***

I get the message:
You need to associate an identity with GitHub before you can create issues with this service.

Selecting the option "Associate Identity" I get the message:

**Oops! Something went wrong
It looks like you've hit an issue in our server API. Do not worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
If you're daring, you may want to try the following:
Give it a few seconds and reload the page.
If all else fails, create an issue with more details.**

**Log Message**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social_auth/decorators.py", line 27, in wrapper
    raise WrongBackend(backend)
WrongBackend
00:57:42 [ERROR] django.request: Internal Server Error: /account/settings/social/associate/github/ (status_code=500 request=<WSGIRequest
path:/account/settings/social/associate/github/,
GET:<QueryDict: {u'next': [u'/organizations/sentry/repos/']}>,
POST:<QueryDict: {}>,
COOKIES:{'sc': 'DlQy0rlVnFZM5eM1niPcADuVtINg4c0C',
 'sentrysid': '.eJxrYKotZNQI5Y1PLC3JiC8tTi2Kz0zxZgzlTEwuySxLzS9KL2SKYGNgYChOzSspqixkDmUpLk3Jj-ABChW4-WSnl7oVpWQ5eUdwAQVKUotLkvPzszNTwVrK84uyU1NChZDMTkpMzk7NSwlVghinV1qSmVOsB5LXc81NzMxxBLKcoGqYi4vzIxiB5hiW6gEAkM82Sw:1ddMrm:Bw7YJF31bYRJY7gdqUqqdoFLOi0'},
META:{u'CSRF_COOKIE': u'DlQy0rlVnFZM5eM1niPcADuVtINg4c0C',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch, br',
 'HTTP_ACCEPT_LANGUAGE': 'pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'sentrysid=".eJxrYKotZNQI5Y1PLC3JiC8tTi2Kz0zxZgzlTEwuySxLzS9KL2SKYGNgYChOzSspqixkDmUpLk3Jj-ABChW4-WSnl7oVpWQ5eUdwAQVKUotLkvPzszNTwVrK84uyU1NChZDMTkpMzk7NSwlVghinV1qSmVOsB5LXc81NzMxxBLKcoGqYi4vzIxiB5hiW6gEAkM82Sw:1ddMrm:Bw7YJF31bYRJY7gdqUqqdoFLOi0"; sc=DlQy0rlVnFZM5eM1niPcADuVtINg4c0C',
 'HTTP_HOST': 'example.com',
 'HTTP_REFERER': 'https://example.com/organizations/sentry/repos/',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '191.255.56.97',
 'HTTP_X_REAL_IP': '191.255.56.97',
 'PATH_INFO': u'/account/settings/social/associate/github/',
 'QUERY_STRING': 'next=%2Forganizations%2Fsentry%2Frepos%2F',
 'REMOTE_ADDR': '191.255.56.97',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/account/settings/social/associate/github/?next=%2Forganizations%2Fsentry%2Frepos%2F',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': '53db031e311e',
 'SERVER_PORT': '9000',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'uwsgi.core': 2,
 'uwsgi.node': '53db031e311e',
 'uwsgi.version': '2.0.15',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7ff5d25a6780>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7ff5d01d68d0>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>)

Sorry about my English!!!!

**Comment by appinteractive** [comment]
@pcmalves hey I have the exact same issue after renaming my organization. Did you find any fix for that isssue?

**Comment by pcmalves** [comment]
@appinteractive I did not find any solution.

**Comment by appinteractive** [comment]
but I did in the meantime: https://github.com/getsentry/sentry-plugins/issues/284
You have to: 
- use the sentry-plugins
- add an oAuth app in your github account
- set the id, secrect, and so on in sentry itself

Hope that helps.
