### ISSUE TITLE
Fail to install dependencies (with sentry 7.7.1)

### ISSUE THREAD

**Issue by baptistedonaux** [ajcrowe/sentry-gitlab#9]
I installed sentry 7.7.1. When I install sentry-gitlab (```pip install sentry-gitlab```) the installation succesful but when I execute CLI command like ```sentry cleanup --days=30```)  I see a conflict with dependencies version.

```
Failed to load app 'gitlab':
Traceback (most recent call last):
  File "/home/sentry/www/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 243, in install_plugins
    plugin = ep.load()
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (kombu 3.0.26 (/home/sentry/www/lib/python2.7/site-packages), Requirement.parse('kombu<3.1,>=3.0.29'), set(['celery']))

Failed to load plugin 'gitlab':
Traceback (most recent call last):
  File "/home/sentry/www/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 255, in install_plugins
    plugin = ep.load()
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/sentry/www/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (kombu 3.0.26 (/home/sentry/www/lib/python2.7/site-packages), Requirement.parse('kombu<3.1,>=3.0.29'), set(['celery']))


```

**Comment by ajcrowe** [comment]
Is this an issue with the plugin? The trace doens't look like it's a problem with the module?

**Comment by baptistedonaux** [comment]
I can't reproduce this fail because I have upgraded Sentry to 8 release.
